insert into usuario (username, role) values ('Raviv', 'Estimator');
insert into usuario (username, role) values ('Manon', 'Estimator');
insert into usuario (username, role) values ('Eleanore', 'Project Manager');
insert into usuario (username, role) values ('Karl', 'Construction Worker');
insert into usuario (username, role) values ('Iolanthe', 'Construction Worker');
insert into usuario (username, role) values ('Starlin', 'Engineer');
insert into usuario (username, role) values ('Jeromy', 'Construction Expeditor');
insert into usuario (username, role) values ('Sergei', 'Construction Foreman');
insert into usuario (username, role) values ('Ardra', 'Estimator');
insert into usuario (username, role) values ('Carlee', 'Construction Manager');
insert into usuario (username, role) values ('Frannie', 'Architect');
insert into usuario (username, role) values ('Cathee', 'Estimator');
insert into usuario (username, role) values ('Rowney', 'Engineer');
insert into usuario (username, role) values ('Faber', 'Construction Foreman');
insert into usuario (username, role) values ('Marve', 'Supervisor');
insert into usuario (username, role) values ('Onfroi', 'Subcontractor');
insert into usuario (username, role) values ('Bridget', 'Engineer');
insert into usuario (username, role) values ('Tomas', 'Engineer');
insert into usuario (username, role) values ('Byram', 'Electrician');
insert into usuario (username, role) values ('Law', 'Construction Foreman');
