insert into Usuario (login, password, role) values ('cmontilla0', 'mQ2~6JuC', 1);
insert into Usuario (login, password, role) values ('awillgrass1', 'eM1/>pgzYpC9+', 1);
insert into Usuario (login, password, role) values ('blodevick2', 'iZ8$IMzo1,q2qtjo', 1);
insert into Usuario (login, password, role) values ('msennett3', 'hF4.C,sf', 2);
insert into Usuario (login, password, role) values ('cdelcastello4', 'lF7+umDCvf', 2);
insert into Usuario (login, password, role) values ('gkingswell5', 'dZ8.*V<6`<(p', 2);
insert into Usuario (login, password, role) values ('jmuriel6', 'fJ2)s%9McWtyFS', 2);
insert into Usuario (login, password, role) values ('jbennison7', 'iN5|@+PY(A', 2);
insert into Usuario (login, password, role) values ('jgarrould8', 'xX6)r?JItuq5', 2);
insert into Usuario (login, password, role) values ('acharlick9', 'qP2<)jV4', 2);



insert into Produto (name, price) values ('Trout - Smoked', 27);
insert into Produto (name, price) values ('Truffle - Whole Black Peeled', 53);
insert into Produto (name, price) values ('Wine - Chianti Classica Docg', 67);
insert into Produto (name, price) values ('Ham - Procutinni', 30);
insert into Produto (name, price) values ('Flour Dark Rye', 43);
insert into Produto (name, price) values ('Cactus Pads', 42);
insert into Produto (name, price) values ('Napkin - Beverge, White 2 - Ply', 58);
insert into Produto (name, price) values ('Chervil - Fresh', 66);
insert into Produto (name, price) values ('Herb Du Provence - Primerba', 36);
insert into Produto (name, price) values ('Muffin - Mix - Creme Brule 15l', 4);
insert into Produto (name, price) values ('Puree - Passion Fruit', 9);
insert into Produto (name, price) values ('Towel Dispenser', 87);
insert into Produto (name, price) values ('Ranchero - Primerba, Paste', 81);
insert into Produto (name, price) values ('Pepper - Cubanelle', 25);
insert into Produto (name, price) values ('Wine - Chateau Timberlay', 50);
insert into Produto (name, price) values ('Soup - Chicken And Wild Rice', 68);
insert into Produto (name, price) values ('Creme De Menth - White', 72);
insert into Produto (name, price) values ('Table Cloth 54x54 White', 97);
insert into Produto (name, price) values ('Mushroom - Enoki, Dry', 64);
insert into Produto (name, price) values ('Pasta - Ravioli', 10);
insert into Produto (name, price) values ('Cheese - Romano, Grated', 48);
insert into Produto (name, price) values ('Bacardi Raspberry', 58);
insert into Produto (name, price) values ('Steampan Lid', 15);
insert into Produto (name, price) values ('French Pastries', 57);
insert into Produto (name, price) values ('Dill - Primerba, Paste', 82);
insert into Produto (name, price) values ('Salt - Celery', 13);
insert into Produto (name, price) values ('Eggplant - Baby', 60);
insert into Produto (name, price) values ('Wine - White, Concha Y Toro', 95);
insert into Produto (name, price) values ('Radish - Black, Winter, Organic', 8);
insert into Produto (name, price) values ('Longos - Assorted Sandwich', 18);
insert into Produto (name, price) values ('Oil - Sunflower', 7);
insert into Produto (name, price) values ('Arizona - Green Tea', 79);
insert into Produto (name, price) values ('Beef Flat Iron Steak', 90);
insert into Produto (name, price) values ('Bread - White, Sliced', 47);
insert into Produto (name, price) values ('Pepper - Paprika, Spanish', 25);
insert into Produto (name, price) values ('Cornstarch', 27);
insert into Produto (name, price) values ('Pumpkin - Seed', 84);
insert into Produto (name, price) values ('Ice Cream Bar - Drumstick', 42);
insert into Produto (name, price) values ('Beer - True North Lager', 79);
insert into Produto (name, price) values ('Shrimp - Baby, Cold Water', 22);
insert into Produto (name, price) values ('Wine - Chateauneuf Du Pape', 84);
insert into Produto (name, price) values ('Beer - Original Organic Lager', 88);
insert into Produto (name, price) values ('Shrimp - 16 - 20 Cooked, Peeled', 79);
insert into Produto (name, price) values ('V8 Splash Strawberry Banana', 49);
insert into Produto (name, price) values ('Chips - Doritos', 33);
insert into Produto (name, price) values ('Wine - Mas Chicet Rose, Vintage', 51);
insert into Produto (name, price) values ('Oil - Olive Bertolli', 85);
insert into Produto (name, price) values ('Beer - Corona', 33);
insert into Produto (name, price) values ('Bread Ww Cluster', 40);
insert into Produto (name, price) values ('Cumin - Ground', 37);
insert into Produto (name, price) values ('Bread - Roll, Soft White Round', 70);
insert into Produto (name, price) values ('Wine - Black Tower Qr', 94);
insert into Produto (name, price) values ('Bread - White Mini Epi', 74);
insert into Produto (name, price) values ('Wine - Soave Folonari', 72);
insert into Produto (name, price) values ('Pepper Squash', 27);
insert into Produto (name, price) values ('Praline Paste', 70);
insert into Produto (name, price) values ('Glaze - Clear', 30);
insert into Produto (name, price) values ('Appetiser - Bought', 66);
insert into Produto (name, price) values ('Quail - Eggs, Fresh', 33);
insert into Produto (name, price) values ('Puff Pastry - Sheets', 92);
insert into Produto (name, price) values ('Beer - Moosehead', 26);
insert into Produto (name, price) values ('Cocoa Feuilletine', 99);
insert into Produto (name, price) values ('Nut - Hazelnut, Ground, Natural', 53);
insert into Produto (name, price) values ('Nantucket - Pomegranate Pear', 14);
insert into Produto (name, price) values ('Soup - Verve - Chipotle Chicken', 11);
insert into Produto (name, price) values ('Beer - Guiness', 8);
insert into Produto (name, price) values ('Remy Red', 85);
insert into Produto (name, price) values ('Lemon Tarts', 99);
insert into Produto (name, price) values ('Puree - Mocha', 30);
insert into Produto (name, price) values ('Squash - Acorn', 61);
insert into Produto (name, price) values ('Wine - Spumante Bambino White', 49);
insert into Produto (name, price) values ('Phyllo Dough', 17);
insert into Produto (name, price) values ('Dill - Primerba, Paste', 55);
insert into Produto (name, price) values ('Melon - Watermelon, Seedless', 97);
insert into Produto (name, price) values ('Cheese - La Sauvagine', 57);
insert into Produto (name, price) values ('Iced Tea - Lemon, 340ml', 53);
insert into Produto (name, price) values ('Lemonade - Island Tea, 591 Ml', 40);
insert into Produto (name, price) values ('Table Cloth 91x91 Colour', 70);
insert into Produto (name, price) values ('Tandoori Curry Paste', 72);
insert into Produto (name, price) values ('Parsley - Fresh', 86);
insert into Produto (name, price) values ('Savory', 80);
insert into Produto (name, price) values ('Bread - Rolls, Corn', 70);
insert into Produto (name, price) values ('Peach - Halves', 16);
insert into Produto (name, price) values ('Vaccum Bag 10x13', 99);
insert into Produto (name, price) values ('Apple - Delicious, Red', 76);
insert into Produto (name, price) values ('Stock - Fish', 69);
insert into Produto (name, price) values ('Mushroom - Morel Frozen', 28);
insert into Produto (name, price) values ('Beer - Mill St Organic', 44);
insert into Produto (name, price) values ('Goulash Seasoning', 67);
insert into Produto (name, price) values ('Wine - Beaujolais Villages', 76);
insert into Produto (name, price) values ('Cocoa Feuilletine', 19);
insert into Produto (name, price) values ('Appetizer - Veg Assortment', 59);
insert into Produto (name, price) values ('Chevere Logs', 66);
insert into Produto (name, price) values ('Soup - Tomato Mush. Florentine', 77);
insert into Produto (name, price) values ('Beef - Bresaola', 63);
insert into Produto (name, price) values ('Clams - Littleneck, Whole', 76);
insert into Produto (name, price) values ('Coffee Cup 8oz 5338cd', 45);
insert into Produto (name, price) values ('Pastry - Cherry Danish - Mini', 77);
insert into Produto (name, price) values ('Anisette - Mcguiness', 48);
insert into Produto (name, price) values ('Cheese - Colby', 54);
